# Generated by Django 5.0 on 2024-01-01 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='agendamento',
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.DateTimeField(help_text='Data de agendamento do serviço.')),
                ('processado', models.BooleanField(default=False, verbose_name='Processado?')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao', to='laveBem.pessoa')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='laveBem.servico', verbose_name='Serviço solicitado')),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='solicitacao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='laveBem.solicitacao'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
