# Generated by Django 5.0 on 2024-01-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='solicitacao',
            new_name='agendamento',
        ),
    ]
