# Generated by Django 5.0 on 2024-01-01 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0002_rename_solicitacao_atendimento_agendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pag', models.CharField(choices=[('1', 'Pix'), ('2', 'Debito'), ('3', 'Crédito')], max_length=10)),
                ('desconto', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='em R$', max_digits=8)),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desconto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
