# Generated by Django 5.0 on 2024-01-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0002_remove_atendimento_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('1', 'Gerente'), ('2', 'Atendente'), ('3', 'Helper')], default=0, max_length=30),
            preserve_default=False,
        ),
    ]
