# Generated by Django 5.0 on 2024-01-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0003_funcionario_cargo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'verbose_name_plural': 'Solicitações'},
        ),
    ]
