# Generated by Django 5.0 on 2024-01-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0003_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.IntegerField(default=0),
        ),
    ]
