# Generated by Django 5.0 on 2024-01-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0005_usuario_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Atendente', 'Atendente'), ('Helper', 'Helper'), ('Cliente', 'Cliente')], default='Cliente', max_length=30),
        ),
    ]
