# Generated by Django 5.0 on 2024-01-03 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0006_alter_usuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL, verbose_name='Nome do cliente'),
        ),
    ]
