# Generated by Django 5.0 on 2024-01-04 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0007_alter_agendamento_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='nome',
            new_name='cliente_id',
        ),
    ]
