# Generated by Django 5.0 on 2024-01-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0008_rename_nome_agendamento_cliente_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cancelar',
            field=models.BooleanField(default=False, verbose_name='Cancelar?'),
        ),
    ]
