# Generated by Django 5.0 on 2024-01-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0009_agendamento_cancelar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='situacao',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=9),
        ),
    ]
