# Generated by Django 5.0 on 2024-01-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0010_alter_atendimento_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data_atendimento',
            field=models.DateTimeField(auto_now=True, help_text='Data do atendimento'),
        ),
    ]
