# Generated by Django 5.0 on 2024-01-07 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0011_alter_atendimento_data_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='atendimento',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='laveBem.agendamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='agendamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='laveBem.agendamento'),
        ),
    ]
