# Generated by Django 5.0 on 2024-01-07 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0012_venda_atendimento_alter_atendimento_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='atendimento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendidos', to='laveBem.agendamento'),
        ),
    ]
