# Generated by Django 5.0 on 2024-01-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0013_alter_venda_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='confirm_venda',
            field=models.BooleanField(default=False, verbose_name='Confirmar venda?'),
        ),
    ]
