# Generated by Django 5.0 on 2024-01-10 02:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('laveBem', '0014_atendimento_confirm_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='hora',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Horário de agendamento do serviço.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(help_text='Data de agendamento do serviço.'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='laveBem.servico', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='agendamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendido', to='laveBem.agendamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='atendimento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendidos', to='laveBem.atendimento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pag',
            field=models.CharField(choices=[('Pix', 'Pix'), ('Debito', 'Debito'), ('Credito', 'Crédito')], max_length=10),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='em R$', max_digits=8, null=True),
        ),
    ]
